batch_size: 16
block_out_channels:
- 64
- 128
- 192
checkpoint_interval: 1000
learning_rate: 0.0001
log_interval: 10
max_grad_norm: 1.0
num_epochs: 1000
num_train_timesteps: 1000
num_workers: 4
output_dir: training/diffusion_prior
sample_size:
- 100
- 100
weight_decay: 0.01
